package ventanas;

import arbolBinario.ArbolBinario;
import dibujarArbolBinario.ArbolGUI;
import herramientas.Funciones;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import juego.Juego;

public class Game extends javax.swing.JFrame {

    private ArbolBinario tree;
    
    public Game() {
        tree = new ArbolBinario();
        tree.ObtenerArbolBinarioTxt();
        
        initComponents();
        this.setSize(new Dimension(300, 300));
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE); 
    }
    
    //Inicio juego
    public void comenzar() {

        boolean otroJuego = true;

        String db = "";

        Juego j = new Juego(tree.getRoot());

        do {
            j.jugar();
            otroJuego = j.respuesta("Desea jugar otra vez?");

            if (!otroJuego) {
                guardarBaseDatos(j.getTree());
            }

        } while (otroJuego);
    }

    /**
     * GUARDA LA BASE DE APRENDIZAJE
     *
     * @param tree
     */
    private void guardarBaseDatos(ArbolBinario tree) {
        this.tree = tree;

        tree.PreOrder(tree.getRoot());
        tree.txt += "\n-";
        tree.InOrder(tree.getRoot());

        if (Funciones.guardarArchivoTxt(Funciones.archivo, tree.txt)) {
            JOptionPane.showMessageDialog(null, "El adivinador ha aprendido algo nuevo! ");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComenzarBtm = new javax.swing.JButton();
        DibujarArbolBtm = new javax.swing.JButton();
        LimpiarBtm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame2"); // NOI18N

        ComenzarBtm.setText("Juego Nuevo");
        ComenzarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarBtmActionPerformed(evt);
            }
        });

        DibujarArbolBtm.setText("Dibujar Arbol");
        DibujarArbolBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarArbolBtmActionPerformed(evt);
            }
        });

        LimpiarBtm.setText("Eliminar base de datos");
        LimpiarBtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarBtmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LimpiarBtm, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(DibujarArbolBtm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComenzarBtm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComenzarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DibujarArbolBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LimpiarBtm, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComenzarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarBtmActionPerformed
        // TODO add your handling code here:
        comenzar();
    }//GEN-LAST:event_ComenzarBtmActionPerformed

    private void DibujarArbolBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarArbolBtmActionPerformed
        // TODO add your handling code here:
        ArbolGUI gui = new ArbolGUI(tree);
    }//GEN-LAST:event_DibujarArbolBtmActionPerformed

    private void LimpiarBtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarBtmActionPerformed
        // TODO add your handling code here:
        if (Funciones.archivo != null) {
            if (Funciones.guardarArchivoTxt(Funciones.archivo, "")) {
                JOptionPane.showMessageDialog(null, "Se eliminó correctamente la base de datos");
                tree.ObtenerArbolBinarioTxt();
            }
        }
    }//GEN-LAST:event_LimpiarBtmActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComenzarBtm;
    private javax.swing.JButton DibujarArbolBtm;
    private javax.swing.JButton LimpiarBtm;
    // End of variables declaration//GEN-END:variables
}
